# Generated by Django 5.2.3 on 2025-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"ordering": ["payment_date"], "verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
