# Generated by Django 5.2.4 on 2025-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_options_alter_payments_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(choices=[("card", "Карта"), ("cache", "Наличные")]),
        ),
    ]
