# Generated by Django 5.2.4 on 2025-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, help_text="Статус УЗ", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, help_text="Последний вход", null=True),
        ),
    ]
