# Generated by Django 5.2.3 on 2025-06-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название курса", max_length=150, verbose_name="Название"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение к курсу",
                        null=True,
                        upload_to="previews/courses/",
                        verbose_name="Превью",
                    ),
                ),
                ("description", models.TextField(help_text="Добавьте описание курса", verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название урока", max_length=150, verbose_name="Название"),
                ),
                ("description", models.TextField(help_text="Добавьте описание урока", verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение к уроку",
                        null=True,
                        upload_to="previews/lessons/",
                        verbose_name="Превью",
                    ),
                ),
                ("video_url", models.URLField(help_text="Добавьте ссылку на видео", verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms.course", verbose_name="Курс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["title", "course"],
            },
        ),
    ]
