# Generated by Django 5.2.3 on 2025-06-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, help_text="Добавьте описание курса", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="Добавьте описание урока", null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Добавьте ссылку на видео", null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
