# Generated by Django 5.2.4 on 2025-07-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
